import { type MutableRefObject } from 'react';
import { type MaskitoOptions } from '@maskito/core';
import { type InputAutocompleteDesktopProps } from '@alfalab/core-components-input-autocomplete/desktop';
import { type GroupShape, type OptionShape } from '@alfalab/core-components-select/shared';
import { type CountriesData } from '../data/country-data';
import { type Country } from '../types';
export declare function initCountries(iso2s?: string[], customCountriesList?: CountriesData[]): Country[][];
export declare function findCountry(countries: Country[][], value: string | undefined, iso2: string | undefined, country?: Country): Country | undefined;
export declare function guessCountry(inputNumber: string, data: Country[][]): Country | undefined;
export declare function clearMask(value: string): string;
export declare function createPhoneMaskExpression(country: Country | undefined, clearableCountryCode: boolean): Array<RegExp | string>;
export declare function createMaskOptions(country: Country | undefined, clearableCountryCode: boolean, preserveCountryCode: boolean, beforeAutofillValueRef: MutableRefObject<string>): MaskitoOptions;
declare function defaultFilterFn(value: string | undefined, option: OptionShape): boolean;
export declare const filterPhones: (value?: string, options?: InputAutocompleteDesktopProps["options"], filterFn?: typeof defaultFilterFn) => (OptionShape | GroupShape)[];
export declare function getPhoneData(phone: string, countries: Country[][], defaultIso2?: string): {
    nextPhone: string;
    nextCountry: Country | undefined;
};
export declare function getClear(clear?: boolean, clearableCountryCode?: boolean, value?: string, countryCode?: string): boolean;
export declare function getInternationalPhoneInputDesktopTestIds(dataTestId: string): {
    fieldAutocompleteWrapper: string;
    fieldAutocompleteInner: string;
    fieldAutocompleteFormControl: string;
    fieldAutocompleteLeftAddons: string;
    fieldAutocompleteRightAddons: string;
    fieldAutocompleteError: string;
    fieldAutocompleteHint: string;
    option: string;
    optionsList: string;
    countryOption: string;
    countryOptionsList: string;
    field: string;
    fieldInner: string;
    fieldFormControl: string;
    fieldLeftAddons: string;
    fieldRightAddons: string;
    fieldError: string;
    fieldHint: string;
};
export declare function getInternationalPhoneInputMobileTestIds(dataTestId: string): {
    fieldAutocompleteWrapper: string;
    fieldAutocompleteInner: string;
    fieldAutocompleteFormControl: string;
    fieldAutocompleteLeftAddons: string;
    fieldAutocompleteRightAddons: string;
    fieldAutocompleteError: string;
    fieldAutocompleteHint: string;
    option: string;
    optionsList: string;
    bottomSheet: string;
    bottomSheetHeader: string;
    bottomSheetContent: string;
    countryOption: string;
    countryOptionsList: string;
    countryBottomSheet: string;
    countryBottomSheetHeader: string;
    countryBottomSheetContent: string;
    clearButton: string;
    applyButton: string;
    field: string;
    fieldInner: string;
    fieldFormControl: string;
    fieldLeftAddons: string;
    fieldRightAddons: string;
    fieldError: string;
    fieldHint: string;
    searchInput: string;
    searchFormControl: string;
    searchInner: string;
    searchLeftAddons: string;
    searchRightAddons: string;
    searchError: string;
    searchHint: string;
};
export declare function getInitialValueFromCountry(countryCode: string): string;
export {};
