import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import process from "node:process";

const packageRoot = resolve(import.meta.dirname, "..");
const sources = {
  primitive: resolve(packageRoot, "src/primitive/primitive.tokens.json"),
  typography: resolve(packageRoot, "src/semantic/typography.tokens.json"),
  brand: resolve(packageRoot, "src/brand/default.brand.tokens.json"),
  darkBrand: resolve(packageRoot, "src/brand/default.dark.brand.tokens.json"),
  light: resolve(packageRoot, "src/themes/light.semantic.tokens.json"),
  dark: resolve(packageRoot, "src/themes/dark.semantic.tokens.json")
};

const outputs = {
  css: resolve(packageRoot, "generated/tokens.css"),
  tailwind: resolve(packageRoot, "generated/tailwind.css"),
  typescript: resolve(packageRoot, "src/generated/tokens.ts")
};

const parse = async (path) => JSON.parse(await readFile(path, "utf8"));

function flatten(node, prefix = [], output = new Map()) {
  if (node && typeof node === "object" && "$value" in node) {
    output.set(prefix.join("."), node);
    return output;
  }

  for (const [key, value] of Object.entries(node)) {
    if (!key.startsWith("$")) flatten(value, [...prefix, key], output);
  }

  return output;
}

function kebab(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\./g, "-")
    .toLowerCase();
}

function variable(path) {
  return `--ds-${kebab(path)}`;
}

function formatValue(value) {
  if (typeof value === "string") {
    const alias = value.match(/^\{([^}]+)\}$/);
    return alias ? `var(${variable(alias[1])})` : value;
  }

  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map((item) => `"${item}"`).join(", ");
  if (
    value
    && typeof value === "object"
    && "fontFamily" in value
    && "fontSize" in value
    && "fontWeight" in value
    && "lineHeight" in value
  ) {
    return [
      formatValue(value.fontWeight),
      `${formatValue(value.fontSize)}/${formatValue(value.lineHeight)}`,
      formatValue(value.fontFamily)
    ].join(" ");
  }
  if (value && typeof value === "object" && "value" in value && "unit" in value) {
    return `${value.value}${value.unit}`;
  }

  throw new Error(`Unsupported token value: ${JSON.stringify(value)}`);
}

function validateAliases(collections) {
  const paths = new Set(collections.flatMap((tokens) => [...tokens.keys()]));

  for (const tokens of collections) {
    for (const [path, token] of tokens) {
      const values = typeof token.$value === "object" && !Array.isArray(token.$value)
        ? Object.values(token.$value)
        : [token.$value];
      for (const value of values) {
        if (typeof value !== "string") continue;
        const alias = value.match(/^\{([^}]+)\}$/);
        if (alias && !paths.has(alias[1])) {
          throw new Error(`Broken alias in ${path}: ${alias[1]}`);
        }
      }
    }
  }
}

function declarations(tokens) {
  return [...tokens]
    .map(([path, token]) => `  ${variable(path)}: ${formatValue(token.$value)};`)
    .join("\n");
}

function semanticTailwindVariables(tokens) {
  return [...tokens.keys()]
    .filter((path) => !path.endsWith("ringWidth"))
    .map((path) => `  --color-${kebab(path)}: var(${variable(path)});`);
}

function typographyUtilities(typography) {
  return [...typography.keys()]
    .map((path) => [
      `@utility typo-${kebab(path).slice(11)} {`,
      `  font: var(${variable(path)});`,
      "}"
    ].join("\n"));
}

function tailwindTheme(primitive, typography, light) {
  const lines = [
    "/* Generated by packages/tokens/scripts/generate.mjs. Do not edit. */",
    "@theme inline {",
    ...semanticTailwindVariables(light)
  ];

  for (const path of primitive.keys()) {
    const name = kebab(path);
    if (path.startsWith("space.")) lines.push(`  --spacing-${name.slice(6)}: var(${variable(path)});`);
    if (path.startsWith("radius.")) lines.push(`  --radius-${name.slice(7)}: var(${variable(path)});`);
    if (path.startsWith("shadow.")) lines.push(`  --shadow-${name.slice(7)}: var(${variable(path)});`);
    if (path.startsWith("breakpoint.")) lines.push(`  --breakpoint-${name.slice(11)}: var(${variable(path)});`);
    if (path.startsWith("font.family.")) lines.push(`  --font-${name.slice(12)}: var(${variable(path)});`);
    if (path.startsWith("font.size.")) lines.push(`  --text-${name.slice(10)}: var(${variable(path)});`);
    if (path.startsWith("size.icon.")) lines.push(`  --spacing-icon-${name.slice(10)}: var(${variable(path)});`);
  }

  lines.push("}", "", ...typographyUtilities(typography), "");
  return lines.join("\n");
}

function typescriptOutput(primitive, typography, brand, darkBrand, light, dark) {
  const object = (tokens) => Object.fromEntries(
    [...tokens].map(([path, token]) => [path, token.$value])
  );

  return [
    "/* Generated by packages/tokens/scripts/generate.mjs. Do not edit. */",
    `export const primitiveTokens = ${JSON.stringify(object(primitive), null, 2)} as const;`,
    `export const typographyTokens = ${JSON.stringify(object(typography), null, 2)} as const;`,
    `export const defaultBrandTokens = ${JSON.stringify(object(brand), null, 2)} as const;`,
    `export const defaultDarkBrandTokens = ${JSON.stringify(object(darkBrand), null, 2)} as const;`,
    `export const lightSemanticTokens = ${JSON.stringify(object(light), null, 2)} as const;`,
    `export const darkSemanticTokens = ${JSON.stringify(object(dark), null, 2)} as const;`,
    "",
    "export type PrimitiveTokenPath = keyof typeof primitiveTokens;",
    "export type TypographyTokenPath = keyof typeof typographyTokens;",
    "export type BrandTokenPath = keyof typeof defaultBrandTokens;",
    "export type SemanticTokenPath = keyof typeof lightSemanticTokens;",
    ""
  ].join("\n\n");
}

const [primitiveSource, typographySource, brandSource, darkBrandSource, lightSource, darkSource] = await Promise.all(
  Object.values(sources).map(parse)
);
const primitive = flatten(primitiveSource);
const typography = flatten(typographySource);
const brand = flatten(brandSource);
const darkBrand = flatten(darkBrandSource);
const light = flatten(lightSource);
const dark = flatten(darkSource);

validateAliases([primitive, typography, brand, darkBrand, light, dark]);

if ([...light.keys()].join("|") !== [...dark.keys()].join("|")) {
  throw new Error("Light and dark semantic token paths must match exactly.");
}
if ([...brand.keys()].join("|") !== [...darkBrand.keys()].join("|")) {
  throw new Error("Light and dark default brand token paths must match exactly.");
}

const generated = {
  css: [
    "/* Generated by packages/tokens/scripts/generate.mjs. Do not edit. */",
    "@layer tokens {",
    "  :root {",
    "    color-scheme: light;",
    declarations(new Map([...primitive, ...typography, ...brand])).replace(/^/gm, "  "),
    "  }",
    "",
    "  :root, [data-theme=\"light\"] {",
    "    color-scheme: light;",
    declarations(light).replace(/^/gm, "  "),
    "  }",
    "",
    "  [data-theme=\"dark\"] {",
    "    color-scheme: dark;",
    declarations(darkBrand).replace(/^/gm, "  "),
    declarations(dark).replace(/^/gm, "  "),
    "  }",
    "",
    "  @media (prefers-reduced-motion: reduce) {",
    "    :root {",
    "      --ds-motion-fast: 0ms;",
    "      --ds-motion-normal: 0ms;",
    "      --ds-motion-slow: 0ms;",
    "    }",
    "  }",
    "}",
    ""
  ].join("\n"),
  tailwind: tailwindTheme(primitive, typography, light),
  typescript: typescriptOutput(primitive, typography, brand, darkBrand, light, dark)
};

let hasMismatch = false;
for (const [key, path] of Object.entries(outputs)) {
  if (process.argv.includes("--check")) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== generated[key]) {
      console.error(`Generated file is stale: ${path}`);
      hasMismatch = true;
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, generated[key], "utf8");
  }
}

if (hasMismatch) process.exitCode = 1;
